***Zadanie 1***


In [3]:
def fib(n: int)->list:
    vect = [1, 1]
    for i in range(n - 2):
        vect.append(vect[i] + vect[i + 1])
    return vect


vect = fib(10
          )
print(vect)
print(len(vect))

[1, 1, 2, 3, 5, 8, 13, 21, 34]
9


***Zadanie 2***


In [5]:
from numpy import zeros
from random import randint

def customMatrix(m: int, n: int)->list:
    tempTab = zeros((m, n))
    if m > n:
        temp = m
    else:
        temp = n
    for j in range(m):
        for i in range(n):
            tempTab[j][i] = temp
    return tempTab


matrix = customMatrix(randint(3, 7), randint(3, 7))
print(matrix)

[[6. 6. 6. 6.]
 [6. 6. 6. 6.]
 [6. 6. 6. 6.]
 [6. 6. 6. 6.]
 [6. 6. 6. 6.]
 [6. 6. 6. 6.]]


***Zadanie 3***


In [6]:
from scipy.linalg import hilbert
from random import randint as rng

matrix = hilbert(rng(3, 7))
print(matrix)

[[1.         0.5        0.33333333 0.25       0.2        0.16666667]
 [0.5        0.33333333 0.25       0.2        0.16666667 0.14285714]
 [0.33333333 0.25       0.2        0.16666667 0.14285714 0.125     ]
 [0.25       0.2        0.16666667 0.14285714 0.125      0.11111111]
 [0.2        0.16666667 0.14285714 0.125      0.11111111 0.1       ]
 [0.16666667 0.14285714 0.125      0.11111111 0.1        0.09090909]]


***Zadanie 4***


In [7]:
import numpy
import scipy

matrix = numpy.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matrix)

lo_matrix = numpy.tril(matrix, 0)
print(lo_matrix)

up_matrix = numpy.triu(matrix, 0)
print(up_matrix)

def myDiag(m: list)->list:
    return numpy.tril(numpy.triu(m))

di_matrix = myDiag(matrix)
print(di_matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 0 0]
 [4 5 0]
 [7 8 9]]
[[1 2 3]
 [0 5 6]
 [0 0 9]]
[[1 0 0]
 [0 5 0]
 [0 0 9]]


***Zadanie 5***

In [8]:
import numpy

matrix = numpy.random.randint(3, 7, size = (3, 3))
print(matrix)

print("max: ", numpy.amax(matrix))
print("min: ", numpy.amin(matrix))
print("mean: ", numpy.mean(matrix))

[[3 5 6]
 [5 5 5]
 [5 3 6]]
max:  6
min:  3
mean:  4.777777777777778


***Zadanie 6***